#!/usr/bin/python
import os, sys
import yaml
import re
from optparse import OptionParser

def yaml_load(filename):
  with open(filename, 'r') as stream:
      try:
          return (yaml.load(stream))
      except yaml.YAMLError as exc:
          print(exc)

def check_args():
  parser = OptionParser()
  parser.add_option("-p", "--role_path", dest="role_path",
                  help="path to the role")
  (options, args) = parser.parse_args()
  if options.role_path is None:
    print options
    sys.exit(2)
  else:
    return options.rolepath

def main():

  check_args()
  return_code = 0
  print "Anna Say :"
  
  try:
    assert(os.path.exists("defaults/main.yml")), "file defaults/main.yml not found"
    assert(os.path.getsize("defaults/main.yml") > 0 ), "file defaults/main.yml is empty"
  except AssertionError as e:
    return_code = 2
    print e
  
  try: 
    assert(os.path.exists("meta")),"folder meta not found"
    assert(os.path.exists("meta/main.yml")), "file meta/main.yml not found"
    assert(os.path.getsize("meta/main.yml") > 0 ), "file meta/main.yml is empty" 
  except AssertionError as e:
    return_code = 2
    print e
  
  try:
    assert(os.path.exists("tasks")),"folder tasks not found"
    assert(os.path.exists("tasks/main.yml")), "file tasks/main.yml not found"
    assert(os.path.getsize("tasks/main.yml") > 0 ), "file tasks/main.yml is empty"
  except AssertionError as e:
    return_code = 2
    print e
  
  try:
    assert(os.path.exists("tasks/install.yml")), "file tasks/install.yml not found"
    assert(os.path.getsize("tasks/install.yml") > 0 ), "file tasks/install.yml is empty"
  except AssertionError as e:
    return_code = 2
    print e
  
  meta=yaml_load("meta/main.yml")
  
  meta["galaxy_info"]["galaxy_tags"][0]
  
  if return_code is 0 :
    print "Everything is fine, keep the good job :)"
  else:
   print "Now i'am sad :("


if __name__ == '__main__':
  main()
  
